DEBUG:Chroma:Logger created
DEBUG:Chroma:Index not found
DEBUG:Chroma:Index saved to /media/gyasis/Blade 15 SSD/Users/gyasi/Google Drive (not syncing)/Collection/ChatLikeQA/data/index/index.bin
DEBUG:Chroma:Index saved to /media/gyasis/Blade 15 SSD/Users/gyasi/Google Drive (not syncing)/Collection/ChatLikeQA/data/index/index.bin
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 101-198-297
DEBUG:Chroma:time to pre process our knn query: 5.0067901611328125e-06
DEBUG:Chroma:time to run knn query: 0.0008702278137207031
INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 19:17:40] "POST /get-response HTTP/1.1" 200 -
DEBUG:Chroma:time to pre process our knn query: 2.86102294921875e-06
DEBUG:Chroma:time to run knn query: 0.0003733634948730469
DEBUG:Chroma:time to pre process our knn query: 4.0531158447265625e-06
DEBUG:Chroma:time to run knn query: 0.0005981922149658203
INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 19:19:23] "POST /get-response HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 19:19:26] "POST /get-response HTTP/1.1" 200 -
WARNING:langchain.llms.openai:Retrying langchain.llms.openai.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')).
WARNING:langchain.llms.openai:Retrying langchain.llms.openai.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')).
WARNING:langchain.llms.openai:Retrying langchain.llms.openai.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')).
WARNING:langchain.llms.openai:Retrying langchain.llms.openai.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')).
WARNING:langchain.llms.openai:Retrying langchain.llms.openai.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')).
DEBUG:Chroma:time to pre process our knn query: 9.5367431640625e-07
DEBUG:Chroma:time to run knn query: 0.0001766681671142578
INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 19:24:08] "POST /get-response HTTP/1.1" 200 -
DEBUG:Chroma:time to pre process our knn query: 1.1920928955078125e-06
DEBUG:Chroma:time to run knn query: 0.00027489662170410156
INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 19:24:16] "POST /get-response HTTP/1.1" 200 -
DEBUG:Chroma:time to pre process our knn query: 1.6689300537109375e-06
DEBUG:Chroma:time to run knn query: 0.00015664100646972656
INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 19:24:20] "POST /get-response HTTP/1.1" 200 -
DEBUG:Chroma:time to pre process our knn query: 2.384185791015625e-06
DEBUG:Chroma:time to run knn query: 0.006269693374633789
INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 19:27:46] "POST /get-response HTTP/1.1" 200 -
WARNING:langchain.embeddings.openai:Retrying langchain.embeddings.openai.embed_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised RateLimitError: The server is currently overloaded with other requests. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists..
DEBUG:Chroma:time to pre process our knn query: 7.152557373046875e-07
DEBUG:Chroma:time to run knn query: 0.0001857280731201172
INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 19:28:05] "POST /get-response HTTP/1.1" 200 -
WARNING:langchain.embeddings.openai:Retrying langchain.embeddings.openai.embed_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised RateLimitError: The server is currently overloaded with other requests. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists..
DEBUG:Chroma:time to pre process our knn query: 3.0994415283203125e-06
DEBUG:Chroma:time to run knn query: 0.0005114078521728516
INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 19:28:58] "POST /get-response HTTP/1.1" 200 -
WARNING:langchain.embeddings.openai:Retrying langchain.embeddings.openai.embed_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIError: The server had an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID df8788fabfa911ebaee554c05bbb49bc in your message.) {
  "error": {
    "message": "The server had an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID df8788fabfa911ebaee554c05bbb49bc in your message.)",
    "type": "server_error",
    "param": null,
    "code": null
  }
}
 500 {'error': {'message': 'The server had an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID df8788fabfa911ebaee554c05bbb49bc in your message.)', 'type': 'server_error', 'param': None, 'code': None}} {'Date': 'Thu, 16 Mar 2023 23:29:32 GMT', 'Content-Type': 'application/json', 'Content-Length': '366', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': '*', 'Openai-Organization': 'user-nriifabwpmnsysihrpmst5bg', 'Openai-Processing-Ms': '30012', 'Openai-Version': '2020-10-01', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains', 'X-Ratelimit-Limit-Requests': '3000', 'X-Ratelimit-Remaining-Requests': '6827', 'X-Ratelimit-Reset-Requests': '136.54', 'X-Request-Id': 'df8788fabfa911ebaee554c05bbb49bc'}.
WARNING:langchain.embeddings.openai:Retrying langchain.embeddings.openai.embed_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIError: The server had an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID c921afbae4f6d1b6cbe6c03089d98de7 in your message.) {
  "error": {
    "message": "The server had an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID c921afbae4f6d1b6cbe6c03089d98de7 in your message.)",
    "type": "server_error",
    "param": null,
    "code": null
  }
}
 500 {'error': {'message': 'The server had an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID c921afbae4f6d1b6cbe6c03089d98de7 in your message.)', 'type': 'server_error', 'param': None, 'code': None}} {'Date': 'Thu, 16 Mar 2023 23:30:06 GMT', 'Content-Type': 'application/json', 'Content-Length': '366', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': '*', 'Openai-Organization': 'user-nriifabwpmnsysihrpmst5bg', 'Openai-Processing-Ms': '30016', 'Openai-Version': '2020-10-01', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains', 'X-Ratelimit-Limit-Requests': '3000', 'X-Ratelimit-Remaining-Requests': '9014', 'X-Ratelimit-Reset-Requests': '180.29', 'X-Request-Id': 'c921afbae4f6d1b6cbe6c03089d98de7'}.
WARNING:langchain.embeddings.openai:Retrying langchain.embeddings.openai.embed_with_retry.<locals>._completion_with_retry in 8.0 seconds as it raised APIError: The server had an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID 3c2ef05524a7029edd6f5e2388625136 in your message.) {
  "error": {
    "message": "The server had an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID 3c2ef05524a7029edd6f5e2388625136 in your message.)",
    "type": "server_error",
    "param": null,
    "code": null
  }
}
 500 {'error': {'message': 'The server had an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID 3c2ef05524a7029edd6f5e2388625136 in your message.)', 'type': 'server_error', 'param': None, 'code': None}} {'Date': 'Thu, 16 Mar 2023 23:30:40 GMT', 'Content-Type': 'application/json', 'Content-Length': '366', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': '*', 'Openai-Organization': 'user-nriifabwpmnsysihrpmst5bg', 'Openai-Processing-Ms': '30011', 'Openai-Version': '2020-10-01', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains', 'X-Ratelimit-Limit-Requests': '3000', 'X-Ratelimit-Remaining-Requests': '10718', 'X-Ratelimit-Reset-Requests': '214.36', 'X-Request-Id': '3c2ef05524a7029edd6f5e2388625136'}.
